spring.application.name=seams-backend
server.port=${SERVER_PORT}

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=31536000000
application.security.jwt.refresh-token.expiration=604800000

# CORS Configuration
application.security.cors.allowed-origins=${ALLOWED_ORIGINS}
